### ISSUE TITLE
Exceptional<T> bool checks Success and Exception and IEnumerableExt FirstOr not accessible in 2.0.0 nuget package

### ISSUE THREAD

**Issue by CarlLanglais** [la-yumba/functional-csharp-code#26]
I have been using version 1.0.0 on .NET 5 in a project for improving my FP knowledge.  I've moved to .NET 6 and upon trying to upgrade from the 1.0.0 to 2.0.0 LaYumba nuget package I receive code errors for Exceptional<T> where if I were performing a check on the Exceptional with Exception or Success bool.

```
resp.Exception == true
```

These checks against Exception or Success are now causing build errors with 2.0.0.  I looked into the definition for Exceptional<T> in VS and 1.0.0 contains the following.

```
public bool Success => Ex == null;
public bool Exception => Ex != null;
```

2.0.0 refactored them to the following.

```
private bool IsSuccess
{
    get;
}

private bool IsException => !IsSuccess;
````

The master branch on Github contains the following.

```
public bool Success => Ex == null;
public bool Exception => Ex != null;
```

I also get the same for FirstOr from IEnumerableExt. 1.0.0 works, move to 2.0.0, can't find it, and master still contains a public generic method for it.

Did I miss a posting that these were to change? Are these permanent changes?

**Comment by la-yumba** [comment]
Hello, 

this library is a bit different from most other projects, in that it was developed for the book. For this reason, version 2 of the library is not based on the code in this repository, but on the code in https://github.com/la-yumba/functional-csharp-code-2 which was created along with the 2nd edition of the book. 

There were some breaking changes between the two version, and I think that's ok. It's a pedagogical library, so backwards compatibility is a priority. Among those changes:

- `IsSuccess` and `IsException` were made private (client code should rely on `Match`)
- `FirstOr` was removed, because .NET 6 introduced an overload of `FirstOrDefault` that takes a fallback value

**Comment by CarlLanglais** [comment]
Thanks for the clarification.
