### ISSUE TITLE
Need help with this code

### ISSUE THREAD

**Issue by moerwald** [la-yumba/functional-csharp-code#28]
Just reading your greate book and studing the code. Can you explain, why Unit is needed in below `SelectMany` function?

```
  public static async Task<RR> SelectMany<R, RR>
         (this Task task, Func<Unit, Task<R>> bind, Func<Unit, R, RR> project)
      {
         await task;
         R r = await bind(Unit());
         return project(Unit(), r);
      }

```

**Comment by la-yumba** [comment]
This is just some "glue" code, to allow LINQ expressions with `Task`s to compile. Normally, in FP, everything returns a value, at least `Unit`, so `Task` should not exist and `Task<Unit>` should be used instead. You could chain this with another expression that takes a `Unit` and returns a `Task<R>`.  But, because many framework functions that complete asynchonously and return no value return `Task`, and in order to relieve the programmer from converting each of those to a `Task<Unit>`-returning function, I've added this overload.
